import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-gradient-to-t to-[#202024] from-[#0D0D10]`}
      >
        {children}
      </body>
    </html>
  );
}
